-- Migration 022: AI editorial metadata (current model)
-- Extends component_editorial with accessibility notes and
-- ai_jobs with editorial_patch_json for generated patches.

-- 1) Accessibility notes (human-editable narrative from AI observations)
ALTER TABLE component_editorial ADD COLUMN accessibility_notes_json TEXT
  CHECK(accessibility_notes_json IS NULL OR (json_valid(accessibility_notes_json) AND json_type(accessibility_notes_json) = 'array'));

-- 2) Editorial patch in AI jobs (structured suggestion generated by LLM)
ALTER TABLE ai_jobs ADD COLUMN editorial_patch_json TEXT
  CHECK(editorial_patch_json IS NULL OR (json_valid(editorial_patch_json) AND json_type(editorial_patch_json) = 'object'));
