-- Migration 022: AI editorial suggestions (DB-first flow)
-- Adds a suggestions table for IA-generated editorial patches,
-- extends component_editorial with accessibility notes,
-- and adds editorial_patch_json to ai_jobs for persistence.

-- 1) AI-generated editorial suggestions (pending → applied|discarded)
-- Only one pending suggestion per component at a time (partial unique index).
-- UNIQUE(component_id, job_id) enables idempotent upsert.
CREATE TABLE IF NOT EXISTS component_editorial_suggestions (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  component_id  INTEGER NOT NULL REFERENCES components(id) ON DELETE CASCADE,
  job_id        TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'applied', 'discarded')),
  patch_json    TEXT NOT NULL CHECK(json_valid(patch_json) AND json_type(patch_json) = 'object'),
  provider      TEXT,
  model         TEXT,
  created_at    INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
  applied_at    INTEGER,
  UNIQUE(component_id, job_id)
);

CREATE INDEX IF NOT EXISTS idx_editorial_suggestions_component_status
  ON component_editorial_suggestions(component_id, status, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_editorial_suggestions_one_pending
  ON component_editorial_suggestions(component_id)
  WHERE status = 'pending';

-- 2) Accessibility notes (human-editable narrative from AI observations)
ALTER TABLE component_editorial ADD COLUMN accessibility_notes_json TEXT
  CHECK(accessibility_notes_json IS NULL OR (json_valid(accessibility_notes_json) AND json_type(accessibility_notes_json) = 'array'));

-- 3) Editorial patch in AI jobs (structured suggestion generated by LLM)
ALTER TABLE ai_jobs ADD COLUMN editorial_patch_json TEXT
  CHECK(editorial_patch_json IS NULL OR (json_valid(editorial_patch_json) AND json_type(editorial_patch_json) = 'object'));
