/**
 * Spec to Markdown Injector
 *
 * Validates and safely injects content between HTML comment boundaries.
 * Used by ds-spec-to-markdown to inject YAML spec data into markdown.
 */

import type {
  SpecAnatomyItem,
  SpecProperty,
  SpecLayoutItem,
  SpecVariant,
  SpecToMarkdownInput,
} from '../types/spec.js';

/**
 * Generate header comment for auto-generated content.
 */
export function makeHeader(slug: string): string {
  return `<!--
  ⚠️ AUTO-GENERATED: DO NOT EDIT
  Source: <active-system-docs>/docs/_spec/components/${slug}.yml
  Generated by: ds-spec-to-markdown
-->\n`;
}

/**
 * Zone processing result.
 */
export interface ZoneProcessResult {
  content: string;
  warning?: string;
}

/**
 * Validates and safely injects content between HTML comment boundaries.
 */
export function processZone(
  markdown: string,
  zoneName: string,
  contentToInject: string,
  slug: string,
): ZoneProcessResult {
  const startTag = `<!-- AUTO-GENERATED-${zoneName}:START -->`;
  const endTag = `<!-- AUTO-GENERATED-${zoneName}:END -->`;

  const startIdx = markdown.indexOf(startTag);
  const endIdx = markdown.indexOf(endTag);

  // Case: Both tags missing - append at end
  if (startIdx === -1 && endIdx === -1) {
    const warning = `[WARNING] Zone tag missing for ${zoneName}. Appending safely at the end of the document.`;
    const appended = markdown.replace(/\n*$/, '') + `\n\n${startTag}\n${makeHeader(slug)}${contentToInject}\n${endTag}\n`;
    return { content: appended, warning };
  }

  // Case: Only one tag missing - corrupted
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(
      `Corrupted boundaries for ${zoneName}: Missing ${startIdx === -1 ? 'START' : 'END'} tag.`,
    );
  }

  // Case: Tags in wrong order
  if (startIdx > endIdx) {
    throw new Error(
      `Corrupted boundaries for ${zoneName}: END tag appears before START tag.`,
    );
  }

  // Case: Multiple occurrences
  const startTagOccurrences = markdown.split(startTag).length - 1;
  const endTagOccurrences = markdown.split(endTag).length - 1;
  if (startTagOccurrences > 1 || endTagOccurrences > 1) {
    throw new Error(`Ambiguity for ${zoneName}: Multiple identical tags found.`);
  }

  // Extract sections
  const before = markdown.slice(0, startIdx + startTag.length);
  const after = markdown.slice(endIdx);
  const newContent = `\n${makeHeader(slug)}${contentToInject}\n`;

  return { content: before + newContent + after };
}

/**
 * Render anatomy section markdown.
 */
export function renderAnatomyMarkdown(anatomy: SpecAnatomyItem[]): string {
  if (!anatomy || anatomy.length === 0) {
    return '- `TBD`\n';
  }

  const lines = anatomy.map((item) => {
    const parts: string[] = [];
    if (item.name) parts.push(`**${item.name}**`);
    if (item.dimensions) {
      const dims: string[] = [];
      if (item.dimensions.width) dims.push(`${item.dimensions.width}px`);
      if (item.dimensions.height) dims.push(`${item.dimensions.height}px`);
      if (dims.length > 0) parts.push(`(${dims.join(' × ')})`);
    }
    if (item.description) parts.push(`— ${item.description}`);
    return `- ${parts.join(' ')}`;
  });

  return lines.join('\n') + '\n';
}

/**
 * Render properties table rows.
 */
export function renderPropertiesTable(properties: SpecProperty[]): string {
  if (!properties || properties.length === 0) {
    return '| TBD | TBD | TBD | TBD | TBD | TBD |';
  }

  return properties
    .map((prop) => {
      const name = prop.name || 'TBD';
      const type = prop.type || 'TBD';
      const defaultValue = prop.default ?? 'TBD';
      const required = prop.required ? 'Yes' : 'No';
      const description = prop.description || 'TBD';
      const notes = prop.notes || 'TBD';
      return `| ${name} | ${type} | ${defaultValue} | ${required} | ${description} | ${notes} |`;
    })
    .join('\n');
}

/**
 * Render layout table rows.
 */
export function renderLayoutTable(layout: SpecLayoutItem[]): string {
  if (!layout || layout.length === 0) {
    return '| TBD | TBD | TBD | TBD | TBD | TBD | TBD |';
  }

  return layout
    .map((item) => {
      const node = item.node || 'TBD';
      const direction = item.direction || 'None';
      const alignment = item.alignment || 'TBD';
      const hSizing = item.hSizing || 'Fixed';
      const vSizing = item.vSizing || 'Fixed';
      const itemSpacing = item.itemSpacing ?? 'TBD';
      const padding = item.padding
        ? `${item.padding.top ?? 0}/${item.padding.right ?? 0}/${item.padding.bottom ?? 0}/${item.padding.left ?? 0}`
        : '0/0/0/0';
      return `| ${node} | ${direction} | ${alignment} | ${hSizing} | ${vSizing} | ${itemSpacing} | ${padding} |`;
    })
    .join('\n');
}

/**
 * Render variant specs for per-variant attributes section.
 */
export function renderVariantSpecs(variants: SpecVariant[]): string {
  if (!variants || variants.length === 0) {
    return '- `TBD`\n';
  }

  const variantProperties = variants.filter(
    (variant) => variant.type === 'variant',
  );

  if (variantProperties.length === 0) {
    return '- Default: `TBD`\n- Other states: `TBD`\n';
  }

  const stateLines: string[] = [];
  for (const property of variantProperties) {
    const values = property.values || [];
    if (values.length === 0) continue;
    for (const value of values) {
      stateLines.push(`- ${property.name || 'State'}=${value}.`);
    }
  }

  return stateLines.length > 0
    ? `${stateLines.join('\n')}\n`
    : '- Default: `TBD`\n- Other states: `TBD`\n';
}

/**
 * Render variant rows for the variants matrix table.
 */
export function renderVariantRows(variants: SpecVariant[]): string {
  if (!variants || variants.length === 0) {
    return '';
  }

  return variants
    .map((variant) => {
      const variantName = variant.name || 'TBD';
      const token = variant.token || 'TBD';
      const fallback = variant.fallback || 'None';
      const notes = variant.notes || 'TBD';
      return `| ${variantName} | ${token} | ${fallback} | ${notes} |`;
    })
    .join('\n');
}

/**
 * Type guard to validate spec input structure.
 */
export function isSpecInput(spec: unknown): spec is SpecToMarkdownInput {
  if (!spec || typeof spec !== 'object') return false;
  const obj = spec as Record<string, unknown>;

  // Validate at least one field is present (empty spec is not useful)
  if (!obj.anatomy && !obj.properties && !obj.layout && !obj.variants) {
    return false;
  }

  // Validate anatomy if present
  if (obj.anatomy !== undefined) {
    if (!Array.isArray(obj.anatomy)) return false;
    for (const item of obj.anatomy) {
      if (!item || typeof item !== 'object') return false;
      const a = item as Record<string, unknown>;
      if (typeof a.name !== 'string') return false;
    }
  }

  // Validate properties if present
  if (obj.properties !== undefined) {
    if (!Array.isArray(obj.properties)) return false;
    for (const p of obj.properties) {
      if (!p || typeof p !== 'object') return false;
      const prop = p as Record<string, unknown>;
      if (typeof prop.name !== 'string') return false;
      if (typeof prop.type !== 'string') return false;
      if (typeof prop.required !== 'boolean') return false;
    }
  }

  // Validate layout if present
  if (obj.layout !== undefined) {
    if (!Array.isArray(obj.layout)) return false;
    for (const item of obj.layout) {
      if (!item || typeof item !== 'object') return false;
      const l = item as Record<string, unknown>;
      if (typeof l.node !== 'string') return false;
      if (typeof l.direction !== 'string') return false;
    }
  }

  // Validate variants if present
  if (obj.variants !== undefined) {
    if (!Array.isArray(obj.variants)) return false;
    for (const v of obj.variants) {
      if (!v || typeof v !== 'object') return false;
      const variant = v as Record<string, unknown>;
      if (typeof variant.name !== 'string') return false;
      if (typeof variant.type !== 'string') return false;
    }
  }

  return true;
}

/**
 * Main injector function result with warnings.
 */
export interface SpecToMarkdownResult {
  content: string;
  warnings: string[];
}

/**
 * Main injector function.
 *
 * @param markdown - The raw markdown file text
 * @param spec - The structured component specification object (already validated by caller)
 * @param slug - The component slug
 * @returns The mutated markdown with safely injected zones and any warnings
 */
export function injectSpecZones(
  markdown: string,
  spec: SpecToMarkdownInput,
  slug: string,
): SpecToMarkdownResult {
  if (typeof markdown !== 'string') {
    throw new Error('Markdown content must be a string.');
  }

  let result = markdown;
  const warnings: string[] = [];

  // 1. Anatomy Zone
  const anatomyContent = renderAnatomyMarkdown(spec.anatomy || []);
  const anatomyResult = processZone(result, 'ANATOMY', anatomyContent, slug);
  if (anatomyResult.warning) warnings.push(anatomyResult.warning);
  result = anatomyResult.content;

  // 2. Properties Zone
  const rawPropsRows = renderPropertiesTable(spec.properties || []);
  const propsTable = `| Name | Type | Default | Required | Description | Narrative Notes |\n| --- | --- | --- | --- | --- | --- |\n${rawPropsRows}`;
  const propsResult = processZone(result, 'PROPERTIES', propsTable, slug);
  if (propsResult.warning) warnings.push(propsResult.warning);
  result = propsResult.content;

  // 3. Visuals Zone (Diffs and Layout)
  const diffs = renderVariantSpecs(spec.variants || []) || '- `TBD`\n';
  const rawLayoutRows = renderLayoutTable(spec.layout || []);
  const layoutTable = `| Node | Direction | Alignment | H Sizing | V Sizing | Item Spacing | Padding (T/R/B/L) |\n| --- | --- | --- | --- | --- | --- | --- |\n${rawLayoutRows}`;
  const visualsContent = `### Per-variant attributes\n\n${diffs}\n### Layout and spacing\n\n${layoutTable}`;
  const visualsResult = processZone(result, 'VISUALS', visualsContent, slug);
  if (visualsResult.warning) warnings.push(visualsResult.warning);
  result = visualsResult.content;

  // 4. Variants Matrix Zone
  const rawVarRows = renderVariantRows(spec.variants || []);
  const matrixContent = `| Variant | Token | Fallback | Notes |\n| --- | --- | --- | --- |\n${rawVarRows}\n`;
  const matrixResult = processZone(result, 'VARIANTS', matrixContent, slug);
  if (matrixResult.warning) warnings.push(matrixResult.warning);
  result = matrixResult.content;

  return { content: result, warnings };
}
