/**
 * Spec to Markdown Injector
 *
 * Inject auto-generated zones from spec YAML into markdown documentation.
 */
import {
  renderAnatomyMarkdown,
  renderPropertiesTable,
  renderLayoutTable,
  renderVariantSpecs,
  renderVariantRows,
} from './spec-renderer.js';

export interface SpecAnatomyItem {
  id: string;
  name: string;
  description?: string;
}

export interface SpecProperty {
  name: string;
  type: string;
  default: string;
  required: boolean;
  description: string;
}

export interface SpecVariant {
  // Manual spec format (from YAML)
  name?: string;
  value?: string;
  token?: string;
  fallback?: string;
  notes?: string;
  
  // Enriched Figma format (from extraction)
  properties?: Record<string, string>;
  fingerprints?: Map<string, {
    nodeType?: string;
    fill?: string;
    stroke?: string;
    textStyle?: string;
    textCase?: string;
    effects?: string[];
  }>;
}

export interface SpecLayout {
  node: string;
  direction: string;
  alignment: string;
  hSizing: string;
  vSizing: string;
  itemSpacing: string | number;
  padding?: {
    top: number;
    right: number;
    bottom: number;
    left: number;
  };
}

export interface ComponentSpec {
  anatomy?: SpecAnatomyItem[];
  properties?: SpecProperty[];
  variants?: SpecVariant[];
  layout?: SpecLayout[];
  [key: string]: unknown;
}

/**
 * Generate HTML comment header for auto-generated content.
 */
function makeHeader(slug: string): string {
  return `<!--
  ⚠️ AUTO-GENERATED: DO NOT EDIT
  Source: docs/_spec/components/${slug}.yml
  Generated by: ds-spec-to-markdown
-->\n`;
}

/**
 * Adapt manual spec variants to enriched format for renderer.
 * Manual format: { name, value, token, fallback }
 * Enriched format: { name, properties, fingerprints }
 * 
 * Preserves manual data in _manual field for renderVariantRows to consume.
 */
function adaptManualVariantsToEnriched(
  variants: SpecVariant[] | undefined | null
): Array<{ name: string; properties: Record<string, string>; fingerprints: Map<string, unknown>; _manual?: { token?: string; fallback?: string; notes?: string } }> {
  if (!variants || variants.length === 0) return [];
  
  return variants.map((variant) => {
    // If already in enriched format, pass through
    if (variant.properties && variant.fingerprints) {
      return variant as { name: string; properties: Record<string, string>; fingerprints: Map<string, unknown>; _manual?: { token?: string; fallback?: string; notes?: string } };
    }
    
    // Convert manual format to enriched format
    const properties: Record<string, string> = {};
    if (variant.name) properties.Variant = variant.name;
    if (variant.value) properties.Value = variant.value;
    
    const fingerprints = new Map<string, unknown>();
    if (variant.token) {
      fingerprints.set('token', { fill: variant.token });
    }
    if (variant.fallback) {
      fingerprints.set('fallback', { note: variant.fallback });
    }
    if (variant.notes) {
      fingerprints.set('notes', { note: variant.notes });
    }
    
    // Preserve manual data for renderVariantRows to consume
    return {
      name: variant.name || 'Variant',
      properties,
      fingerprints,
      _manual: {
        token: variant.token,
        fallback: variant.fallback,
        notes: variant.notes,
      },
    };
  });
}

/**
 * Validates and safely injects content between HTML comment boundaries.
 */
function processZone(
  markdown: string,
  zoneName: string,
  contentToInject: string,
  slug: string
): string {
  const startTag = `<!-- AUTO-GENERATED-${zoneName}:START -->`;
  const endTag = `<!-- AUTO-GENERATED-${zoneName}:END -->`;

  const startIdx = markdown.indexOf(startTag);
  const endIdx = markdown.indexOf(endTag);

  if (startIdx === -1 && endIdx === -1) {
    console.warn(
      `[WARNING] Zone tag missing for ${zoneName}. Appending safely at the end of the document.`
    );
    return (
      markdown.replace(/\n*$/, '') +
      `\n\n${startTag}\n${makeHeader(slug)}${contentToInject}\n${endTag}\n`
    );
  }

  if (startIdx === -1 || endIdx === -1) {
    throw new Error(
      `Corrupted boundaries for ${zoneName}: Missing ${startIdx === -1 ? 'START' : 'END'} tag.`
    );
  }

  if (startIdx > endIdx) {
    throw new Error(
      `Corrupted boundaries for ${zoneName}: END tag appears before START tag.`
    );
  }

  const startTagOccurrences = markdown.split(startTag).length - 1;
  const endTagOccurrences = markdown.split(endTag).length - 1;
  if (startTagOccurrences > 1 || endTagOccurrences > 1) {
    throw new Error(
      `Ambiguity for ${zoneName}: Multiple identical tags found.`
    );
  }

  const before = markdown.slice(0, startIdx + startTag.length);
  const after = markdown.slice(endIdx);
  const newContent = `\n${makeHeader(slug)}${contentToInject}\n`;

  return before + newContent + after;
}

/**
 * Main Injector - Inject spec zones into markdown.
 *
 * @param markdown - The raw markdown file text
 * @param spec - The structured component specification object
 * @param slug - The component slug
 * @returns The mutated markdown with safely injected zones
 */
export function injectSpecZones(
  markdown: string,
  spec: ComponentSpec,
  slug: string
): string {
  if (typeof markdown !== 'string') {
    throw new Error('Markdown content must be a string.');
  }
  if (!spec || typeof spec !== 'object') {
    throw new Error('YAML spec must be a valid object.');
  }

  let result = markdown;

  // 1. Anatomy Zone
  const anatomyContent = renderAnatomyMarkdown(spec.anatomy || []);
  result = processZone(result, 'ANATOMY', anatomyContent, slug);

  // 2. Properties Zone
  const rawPropsRows = renderPropertiesTable(spec.properties || []);
  const propsTable =
    '| Name | Type | Default | Required | Description | Narrative Notes |\n' +
    '| --- | --- | --- | --- | --- | --- |\n' +
    rawPropsRows;
  result = processZone(result, 'PROPERTIES', propsTable, slug);

  // 3. Visuals Zone (Diffs and Layout)
  const adaptedVariants = adaptManualVariantsToEnriched(spec.variants || []);
  const diffs = renderVariantSpecs(adaptedVariants) || '- `TBD`\n';
  const rawLayoutRows = renderLayoutTable(spec.layout || []);
  const layoutTable =
    '| Node | Direction | Alignment | H Sizing | V Sizing | Item Spacing | Padding (T/R/B/L) |\n' +
    '| --- | --- | --- | --- | --- | --- | --- |\n' +
    rawLayoutRows;
  const visualsContent =
    `### Per-variant attributes\n\n${diffs}\n### Layout and spacing\n\n${layoutTable}`;
  result = processZone(result, 'VISUALS', visualsContent, slug);

  // 4. Variants Matrix Zone
  const rawVarRows = renderVariantRows(adaptedVariants);
  const matrixContent =
    '| Variant | Token | Fallback | Notes |\n' +
    '| --- | --- | --- | --- |\n' +
    rawVarRows + '\n';
  result = processZone(result, 'VARIANTS', matrixContent, slug);

  return result;
}
