/**
 * Spec to Markdown Injector
 *
 * Inject auto-generated zones from spec YAML into markdown documentation.
 */
import {
  renderAnatomyMarkdown,
  renderPropertiesTable,
  renderLayoutTable,
  renderVariantSpecs,
  renderVariantRows,
  type SpecAnatomyItem as RenderAnatomyItem,
  type SpecVariantFingerprint,
} from './spec-renderer.js';
import type { SpecAnatomyItem, SpecProperty as SpecPropertyType, SpecVariant, SpecLayoutItem } from '../types/spec.js';
import type { SpecProperty as RendererSpecProperty, SpecLayoutRow } from './spec-renderer.js';

// Local alias for SpecLayoutItem to maintain compatibility with existing code
export type SpecLayout = SpecLayoutItem;

/**
 * Manual variant format (from YAML) - distinct from enriched Figma format.
 */
export interface ManualSpecVariant {
  name?: string;
  value?: string;
  token?: string;
  fallback?: string;
  notes?: string;
}

/**
 * Enriched variant format (from Figma extraction).
 */
export interface EnrichedSpecVariant extends SpecVariantFingerprint {
  _manual?: {
    token?: string;
    fallback?: string;
    notes?: string;
  };
}

/**
 * Component spec with explicit metadata field for extensibility.
 */
export interface ComponentSpec {
  anatomy?: SpecAnatomyItem[];
  properties?: SpecPropertyType[];
  variants?: (ManualSpecVariant | EnrichedSpecVariant)[];
  layout?: SpecLayoutItem[];
  metadata?: Record<string, unknown>;
}

/**
 * Generate HTML comment header for auto-generated content.
 */
function makeHeader(slug: string): string {
  return `<!--
  ⚠️ AUTO-GENERATED: DO NOT EDIT
  Source: docs/_spec/components/${slug}.yml
  Generated by: ds-spec-to-markdown
-->\n`;
}

/**
 * Type guard to check if variant is already in enriched format.
 * Checks for EITHER properties OR fingerprints to catch partially enriched variants.
 */
function isEnrichedSpecVariant(variant: unknown): variant is EnrichedSpecVariant {
  return (
    typeof variant === 'object' &&
    variant !== null &&
    ('properties' in variant || 'fingerprints' in variant)
  );
}

/**
 * Type guard to validate ManualSpecVariant shape.
 * Excludes any variant with properties or fingerprints (enriched format markers).
 */
function isManualSpecVariant(variant: unknown): variant is ManualSpecVariant {
  return (
    typeof variant === 'object' &&
    variant !== null &&
    !('properties' in variant || 'fingerprints' in variant) &&
    ('name' in variant || 'value' in variant || 'token' in variant || 'fallback' in variant || 'notes' in variant)
  );
}

/**
 * Adapt manual spec variants to enriched format for renderer.
 * Manual format: { name, value, token, fallback }
 * Enriched format: { name, properties, fingerprints }
 *
 * Preserves manual data in _manual field for renderVariantRows to consume.
 * Pass-through enriched variants unchanged.
 * Filters out invalid variants (returns null) to prevent 'Unknown' rows in output.
 */
function adaptManualVariantsToEnriched(
  variants: (ManualSpecVariant | EnrichedSpecVariant)[] | undefined | null
): EnrichedSpecVariant[] {
  if (!variants || variants.length === 0) return [];

  return variants.flatMap((variant) => {
    // Pass-through: already in enriched format
    if (isEnrichedSpecVariant(variant)) {
      return [variant];
    }

    // Drop invalid variant objects to avoid rendering placeholder rows.
    if (!isManualSpecVariant(variant)) {
      return [];
    }

    // Convert manual format to enriched format
    const properties: Record<string, string> = {};
    if (variant.name) properties.Variant = variant.name;
    if (variant.value) properties.Value = variant.value;

    const fingerprints = new Map<string, {
      nodeType?: string;
      fill?: string;
      stroke?: string;
      textStyle?: string;
      textCase?: string;
      effects?: string[];
    }>();
    if (variant.token) {
      fingerprints.set('token', { fill: variant.token });
    }

    // Preserve manual data for renderVariantRows to consume
    return {
      name: variant.name || 'Variant',
      properties,
      fingerprints,
      _manual: {
        token: variant.token,
        fallback: variant.fallback,
        notes: variant.notes,
      },
    };
  });
}

/**
 * Validates and safely injects content between HTML comment boundaries.
 */
function processZone(
  markdown: string,
  zoneName: string,
  contentToInject: string,
  slug: string
): string {
  const startTag = `<!-- AUTO-GENERATED-${zoneName}:START -->`;
  const endTag = `<!-- AUTO-GENERATED-${zoneName}:END -->`;

  const startIdx = markdown.indexOf(startTag);
  const endIdx = markdown.indexOf(endTag);

  if (startIdx === -1 && endIdx === -1) {
    console.warn(
      `[WARNING] Zone tag missing for ${zoneName}. Appending safely at the end of the document.`
    );
    return (
      markdown.replace(/\n*$/, '') +
      `\n\n${startTag}\n${makeHeader(slug)}${contentToInject}\n${endTag}\n`
    );
  }

  if (startIdx === -1 || endIdx === -1) {
    throw new Error(
      `Corrupted boundaries for ${zoneName}: Missing ${startIdx === -1 ? 'START' : 'END'} tag.`
    );
  }

  if (startIdx > endIdx) {
    throw new Error(
      `Corrupted boundaries for ${zoneName}: END tag appears before START tag.`
    );
  }

  const startTagOccurrences = markdown.split(startTag).length - 1;
  const endTagOccurrences = markdown.split(endTag).length - 1;
  if (startTagOccurrences > 1 || endTagOccurrences > 1) {
    throw new Error(
      `Ambiguity for ${zoneName}: Multiple identical tags found.`
    );
  }

  const before = markdown.slice(0, startIdx + startTag.length);
  const after = markdown.slice(endIdx);
  const newContent = `\n${makeHeader(slug)}${contentToInject}\n`;

  return before + newContent + after;
}

function toRendererAnatomyItems(
  anatomy: SpecAnatomyItem[] | undefined,
): RenderAnatomyItem[] {
  if (!Array.isArray(anatomy) || anatomy.length === 0) return [];
  return anatomy.map((item, index) => ({
    id: String(item.id || `${item.name || 'part'}-${index + 1}`),
    name: item.name,
  }));
}

/**
 * Map SpecProperty from types/spec.ts to renderer SpecProperty format.
 */
function toRendererSpecProperties(
  properties: SpecPropertyType[] | undefined,
): RendererSpecProperty[] {
  if (!Array.isArray(properties) || properties.length === 0) return [];
  return properties.map((prop) => ({
    name: prop.name,
    type: prop.type,
    default: prop.default !== undefined ? String(prop.default) : undefined,
    required: prop.required,
    description: prop.description,
  }));
}

/**
 * Map SpecLayoutItem from types/spec.ts to renderer SpecLayoutRow format.
 */
function toRendererLayoutRows(
  layout: SpecLayoutItem[] | undefined,
): SpecLayoutRow[] {
  if (!Array.isArray(layout) || layout.length === 0) return [];
  return layout.map((row) => ({
    node: row.node,
    direction: row.direction,
    alignment: row.alignment,
    hSizing: row.hSizing,
    vSizing: row.vSizing,
    itemSpacing: row.itemSpacing !== undefined ? row.itemSpacing : '-',
    padding: row.padding as SpecLayoutRow['padding'],
  }));
}

/**
 * Main Injector - Inject spec zones into markdown.
 *
 * @param markdown - The raw markdown file text
 * @param spec - The structured component specification object
 * @param slug - The component slug
 * @returns The mutated markdown with safely injected zones
 */
export function injectSpecZones(
  markdown: string,
  spec: ComponentSpec,
  slug: string
): string {
  if (typeof markdown !== 'string') {
    throw new Error('Markdown content must be a string.');
  }
  if (!spec || typeof spec !== 'object') {
    throw new Error('YAML spec must be a valid object.');
  }

  let result = markdown;

  // 1. Anatomy Zone
  const anatomyContent = renderAnatomyMarkdown(
    toRendererAnatomyItems(spec.anatomy),
  );
  result = processZone(result, 'ANATOMY', anatomyContent, slug);

  // 2. Properties Zone
  const rawPropsRows = renderPropertiesTable(toRendererSpecProperties(spec.properties));
  const propsTable =
    '| Name | Type | Default | Required | Description | Narrative Notes |\n' +
    '| --- | --- | --- | --- | --- | --- |\n' +
    rawPropsRows;
  result = processZone(result, 'PROPERTIES', propsTable, slug);

  // 3. Visuals Zone (Diffs and Layout)
  const adaptedVariants = adaptManualVariantsToEnriched(spec.variants);
  const diffs = renderVariantSpecs(adaptedVariants) || '- `TBD`\n';
  const rawLayoutRows = renderLayoutTable(toRendererLayoutRows(spec.layout));
  const layoutTable =
    '| Node | Direction | Alignment | H Sizing | V Sizing | Item Spacing | Padding (T/R/B/L) |\n' +
    '| --- | --- | --- | --- | --- | --- | --- |\n' +
    rawLayoutRows;
  const visualsContent =
    `### Per-variant attributes\n\n${diffs}\n### Layout and spacing\n\n${layoutTable}`;
  result = processZone(result, 'VISUALS', visualsContent, slug);

  // 4. Variants Matrix Zone
  const rawVarRows = renderVariantRows(adaptedVariants);
  const matrixContent =
    '| Variant | Token | Fallback | Notes |\n' +
    '| --- | --- | --- | --- |\n' +
    rawVarRows + '\n';
  result = processZone(result, 'VARIANTS', matrixContent, slug);

  return result;
}
