import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { FormField } from '@/components/common';
import {
  Modal,
  ModalCloseButton,
  ModalContent,
  ModalHeader,
  ModalFooter,
} from '@/components/ui/overlay/modal';
import { StatusAlert } from '@/components/ui/status-alert';
import { addConsumer, type AddConsumerPayload } from '@/lib/api';
import { API_ERROR_CODES } from '@/lib/api-errors';
import { toApiErrorDisplay } from '@/lib/api-error-ux';
import { useDesignSystem } from '@/lib/design-system-context';
import { toSystemConsumerDetail } from '@/lib/routes';
import { ApiErrorMessage } from '@/components/api-error-message';
import {
  updateConsumerNameFromFigmaUrlChange,
} from '@/features/consumers/lib/consumer-name-suggestion';

interface AddConsumerModalProps {
  open: boolean;
  onClose: () => void;
  dsFileKey: string;
  onSuccess?: () => void | Promise<void>;
}

export function AddConsumerModal({
  open,
  onClose,
  dsFileKey,
  onSuccess,
}: AddConsumerModalProps) {
  const navigate = useNavigate();
  const { activeSystem } = useDesignSystem();
  const [consumerName, setConsumerName] = useState('');
  const [consumerFileUrl, setConsumerFileUrl] = useState('');
  const [consumerNameWasAutoGenerated, setConsumerNameWasAutoGenerated] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<ReturnType<
    typeof toApiErrorDisplay
  > | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    setError(null);

    try {
      const payload: AddConsumerPayload = {
        dsFileKey,
        consumerName: consumerName.trim(),
        consumerFileUrl: consumerFileUrl.trim() || undefined,
      };

      const created = await addConsumer(payload);
      const consumerId = String(created?.data?.id || '').trim();
      if (!consumerId) {
        throw new Error('Consumer file was created without a valid consumer ID.');
      }

      await onSuccess?.();
      if (activeSystem) {
        navigate(toSystemConsumerDetail(activeSystem, consumerName.trim()));
      }
      handleClose();
    } catch (cause) {
      setError(
        toApiErrorDisplay(cause, {
          fallbackTitle: 'Add or sync failed',
          fallbackMessage: 'Unable to add and sync consumer file.',
        }),
      );
    } finally {
      setSubmitting(false);
    }
  };

  const handleClose = () => {
    setConsumerName('');
    setConsumerFileUrl('');
    setConsumerNameWasAutoGenerated(false);
    setError(null);
    onClose();
  };

  const handleConsumerNameChange = (value: string) => {
    setConsumerName(value);
    setConsumerNameWasAutoGenerated(false);
  };

  const handleConsumerFileUrlChange = (value: string) => {
    setConsumerFileUrl(value);

    const nextState = updateConsumerNameFromFigmaUrlChange({
      consumerName,
      consumerNameWasAutoGenerated,
      consumerFileUrl: value,
    });

    setConsumerName(nextState.consumerName);
    setConsumerNameWasAutoGenerated(nextState.consumerNameWasAutoGenerated);
  };

  return (
    <Modal open={open} onClose={handleClose}>
      <ModalContent size="md">
        <form onSubmit={handleSubmit}>
          <ModalHeader className="items-start gap-4">
            <div className="min-w-0 flex-1">
              <h2 className="text-lg font-titles font-semibold tracking-tight titles-color">
                Add Consumer File
              </h2>
            </div>
            <ModalCloseButton
              onClick={handleClose}
              label="Close add consumer dialog"
            />
          </ModalHeader>
          <div className="space-y-4 p-5">
            {error ? (
              <ApiErrorMessage
                error={error}
                tone={
                  error.code === API_ERROR_CODES.DEPS_CONSUMER_NO_PARENT_USAGE
                    ? 'warning'
                    : 'error'
                }
              />
            ) : null}

            <StatusAlert variant="info" title="How it works">
              Open the plugin in the file that uses a parent design system. Fill in its url and
              name.
            </StatusAlert>

            <FormField id="consumer-file-url" label="Figma file URL" required>
              <Input
                id="consumer-file-url"
                value={consumerFileUrl}
                onChange={(e) => handleConsumerFileUrlChange(e.target.value)}
                placeholder="https://www.figma.com/file/..."
                disabled={submitting}
                required
              />
            </FormField>

            <FormField id="consumer-name" label="Consumer name" required>
              <Input
                id="consumer-name"
                value={consumerName}
                onChange={(e) => handleConsumerNameChange(e.target.value)}
                placeholder="e.g., Marketing Website, Admin Dashboard"
                disabled={submitting}
                required
              />
            </FormField>
          </div>
          <ModalFooter>
            <Button
              type="button"
              variant="outline"
              onClick={handleClose}
              disabled={submitting}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={
                submitting || !consumerName.trim() || !consumerFileUrl.trim()
              }
            >
              {submitting ? 'Adding and syncing...' : 'Add Consumer'}
            </Button>
          </ModalFooter>
        </form>
      </ModalContent>
    </Modal>
  );
}
