graph TD
  N1["A11y.A11y.Dimension.Min-Hit-Area"]
  N2["Components.Bottom-Bar.Background-Default"]
  N3["Components.Bottom-Bar.Background-Selected"]
  N4["Primitives.Color.Blue.100"]
  N5["Primitives.Color.Blue.200"]
  N6["Primitives.Color.Blue.300"]
  N7["Primitives.Color.Blue.400"]
  N8["Primitives.Color.Blue.500"]
  N9["Primitives.Color.Blue.600"]
  N10["Primitives.Color.Blue.700"]
  N11["Primitives.Color.Blue.800"]
  N12["Primitives.Color.Blue.900"]
  N13["Primitives.Color.BW.Black"]
  N14["Primitives.Color.BW.Black-05"]
  N15["Primitives.Color.BW.Black-07"]
  N16["Primitives.Color.BW.Black-10"]
  N17["Primitives.Color.BW.Black-16"]
  N18["Primitives.Color.BW.Black-20"]
  N19["Primitives.Color.BW.White"]
  N20["Primitives.Color.Cucumber.100"]
  N21["Primitives.Color.Cucumber.200"]
  N22["Primitives.Color.Cucumber.300"]
  N23["Primitives.Color.Cucumber.400"]
  N24["Primitives.Color.Cucumber.500"]
  N25["Primitives.Color.Cucumber.600"]
  N26["Primitives.Color.Cucumber.700"]
  N27["Primitives.Color.Cucumber.800"]
  N28["Primitives.Color.Cucumber.900"]
  N29["Primitives.Color.Extra-Palette.Bermuda"]
  N30["Primitives.Color.Extra-Palette.English-Cream"]
  N31["Primitives.Color.Extra-Palette.Lavender"]
  N32["Primitives.Color.Extra-Palette.Lime-Cream"]
  N33["Primitives.Color.Extra-Palette.Moon-Raker"]
  N34["Primitives.Color.Grey.100"]
  N35["Primitives.Color.Grey.200"]
  N36["Primitives.Color.Grey.300"]
  N37["Primitives.Color.Grey.400"]
  N38["Primitives.Color.Grey.500"]
  N39["Primitives.Color.Grey.600"]
  N40["Primitives.Color.Grey.700"]
  N41["Primitives.Color.Grey.800"]
  N42["Primitives.Color.Grey.900"]
  N43["Primitives.Color.Ocean-Green.100"]
  N44["Primitives.Color.Ocean-Green.200"]
  N45["Primitives.Color.Ocean-Green.300"]
  N46["Primitives.Color.Ocean-Green.400"]
  N47["Primitives.Color.Ocean-Green.500"]
  N48["Primitives.Color.Ocean-Green.600"]
  N49["Primitives.Color.Ocean-Green.700"]
  N50["Primitives.Color.Ocean-Green.800"]
  N51["Primitives.Color.Ocean-Green.900"]
  N52["Primitives.Color.Raw-Umber.100"]
  N53["Primitives.Color.Raw-Umber.200"]
  N54["Primitives.Color.Raw-Umber.300"]
  N55["Primitives.Color.Raw-Umber.400"]
  N56["Primitives.Color.Raw-Umber.500"]
  N57["Primitives.Color.Raw-Umber.600"]
  N58["Primitives.Color.Raw-Umber.700"]
  N59["Primitives.Color.Raw-Umber.800"]
  N60["Primitives.Color.Raw-Umber.900"]
  N61["Primitives.Color.Red.100"]
  N62["Primitives.Color.Red.200"]
  N63["Primitives.Color.Red.300"]
  N64["Primitives.Color.Red.400"]
  N65["Primitives.Color.Red.500"]
  N66["Primitives.Color.Red.600"]
  N67["Primitives.Color.Red.700"]
  N68["Primitives.Color.Red.800"]
  N69["Primitives.Color.Red.900"]
  N70["Primitives.Dimension.A11y.Min-Hit-Area-Desktop-AA"]
  N71["Primitives.Dimension.A11y.Min-Hit-Area-Mobile-AAA"]
  N72["Primitives.Dimension.Border.Radius.1000"]
  N73["Primitives.Dimension.Border.Radius.11"]
  N74["Primitives.Dimension.Border.Radius.12"]
  N75["Primitives.Dimension.Border.Radius.16"]
  N76["Primitives.Dimension.Border.Radius.4"]
  N77["Primitives.Dimension.Border.Radius.8"]
  N78["Primitives.Dimension.Border.Radius.9"]
  N79["Primitives.Dimension.Border.Width.1"]
  N80["Primitives.Dimension.Border.Width.2"]
  N81["Primitives.Dimension.Shadow.Blur.12"]
  N82["Primitives.Dimension.Shadow.Blur.16"]
  N83["Primitives.Dimension.Shadow.Blur.20"]
  N84["Primitives.Dimension.Shadow.Blur.8"]
  N85["Primitives.Dimension.Shadow.Spread.-12"]
  N86["Primitives.Dimension.Shadow.Spread.-16"]
  N87["Primitives.Dimension.Shadow.Spread.-2"]
  N88["Primitives.Dimension.Shadow.Spread.-4"]
  N89["Primitives.Dimension.Shadow.Spread.-6"]
  N90["Primitives.Dimension.Shadow.Spread.-8"]
  N91["Primitives.Dimension.Shadow.Spread.0"]
  N92["Primitives.Dimension.Shadow.X.-10"]
  N93["Primitives.Dimension.Shadow.X.-12"]
  N94["Primitives.Dimension.Shadow.X.-16"]
  N95["Primitives.Dimension.Shadow.X.-18"]
  N96["Primitives.Dimension.Shadow.X.-2"]
  N97["Primitives.Dimension.Shadow.X.-4"]
  N98["Primitives.Dimension.Shadow.X.-8"]
  N99["Primitives.Dimension.Shadow.X.0"]
  N100["Primitives.Dimension.Shadow.X.10"]
  N101["Primitives.Dimension.Shadow.X.12"]
  N102["Primitives.Dimension.Shadow.X.16"]
  N103["Primitives.Dimension.Shadow.X.18"]
  N104["Primitives.Dimension.Shadow.X.2"]
  N105["Primitives.Dimension.Shadow.X.4"]
  N106["Primitives.Dimension.Shadow.X.8"]
  N107["Primitives.Dimension.Shadow.Y.-10"]
  N108["Primitives.Dimension.Shadow.Y.-12"]
  N109["Primitives.Dimension.Shadow.Y.-16"]
  N110["Primitives.Dimension.Shadow.Y.-18"]
  N111["Primitives.Dimension.Shadow.Y.-2"]
  N112["Primitives.Dimension.Shadow.Y.-4"]
  N113["Primitives.Dimension.Shadow.Y.-6"]
  N114["Primitives.Dimension.Shadow.Y.-8"]
  N115["Primitives.Dimension.Shadow.Y.0"]
  N116["Primitives.Dimension.Shadow.Y.10"]
  N117["Primitives.Dimension.Shadow.Y.12"]
  N118["Primitives.Dimension.Shadow.Y.16"]
  N119["Primitives.Dimension.Shadow.Y.18"]
  N120["Primitives.Dimension.Shadow.Y.2"]
  N121["Primitives.Dimension.Shadow.Y.4"]
  N122["Primitives.Dimension.Shadow.Y.6"]
  N123["Primitives.Dimension.Shadow.Y.8"]
  N124["Primitives.Dimension.Spacing.10"]
  N125["Primitives.Dimension.Spacing.12"]
  N126["Primitives.Dimension.Spacing.14"]
  N127["Primitives.Dimension.Spacing.16"]
  N128["Primitives.Dimension.Spacing.2"]
  N129["Primitives.Dimension.Spacing.24"]
  N130["Primitives.Dimension.Spacing.32"]
  N131["Primitives.Dimension.Spacing.4"]
  N132["Primitives.Dimension.Spacing.40"]
  N133["Primitives.Dimension.Spacing.48"]
  N134["Primitives.Dimension.Spacing.6"]
  N135["Primitives.Dimension.Spacing.8"]
  N136["Semantic.Color.Background.Action.Danger.Active"]
  N137["Semantic.Color.Background.Action.Danger.Default"]
  N138["Semantic.Color.Background.Action.Danger.Hover"]
  N139["Semantic.Color.Background.Action.Disabled.Default"]
  N140["Semantic.Color.Background.Action.Primary.Active"]
  N141["Semantic.Color.Background.Action.Primary.Default"]
  N142["Semantic.Color.Background.Action.Primary.Hover"]
  N143["Semantic.Color.Background.Action.Secondary.Active"]
  N144["Semantic.Color.Background.Action.Secondary.Default"]
  N145["Semantic.Color.Background.Action.Secondary.Hover"]
  N146["Semantic.Color.Background.Brand.Primary"]
  N147["Semantic.Color.Background.Brand.Secondary"]
  N148["Semantic.Color.Background.Brand.Secondary-Dark"]
  N149["Semantic.Color.Background.Brand.Tertiary"]
  N150["Semantic.Color.Background.Decorative.100"]
  N151["Semantic.Color.Background.Decorative.200"]
  N152["Semantic.Color.Background.Decorative.300"]
  N153["Semantic.Color.Background.Decorative.400"]
  N154["Semantic.Color.Background.Decorative.500"]
  N155["Semantic.Color.Background.Decorative.600"]
  N156["Semantic.Color.Background.Feedback.Default"]
  N157["Semantic.Color.Background.Overlay.Media"]
  N158["Semantic.Color.Background.Overlay.Modal"]
  N159["Semantic.Color.Background.Surface.Card"]
  N160["Semantic.Color.Background.Surface.Control"]
  N161["Semantic.Color.Border.Feedback.Danger"]
  N162["Semantic.Color.Border.Feedback.Information"]
  N163["Semantic.Color.Border.Feedback.Success"]
  N164["Semantic.Color.Border.Neutral.Alpha-05"]
  N165["Semantic.Color.Border.Neutral.Alpha-10"]
  N166["Semantic.Color.Border.Neutral.Alpha-20"]
  N167["Semantic.Color.Border.Neutral.Default"]
  N168["Semantic.Color.Border.Neutral.Emphasis"]
  N169["Semantic.Color.Border.Neutral.Subtle"]
  N170["Semantic.Color.Focus-Outline.Inner"]
  N171["Semantic.Color.Focus-Outline.Outer"]
  N172["Semantic.Color.Icon.Action.On-Danger"]
  N173["Semantic.Color.Icon.Action.On-Disabled"]
  N174["Semantic.Color.Icon.Action.On-Primary"]
  N175["Semantic.Color.Icon.Action.On-Secondary"]
  N176["Semantic.Color.Icon.Feedback.Danger"]
  N177["Semantic.Color.Icon.Feedback.Information"]
  N178["Semantic.Color.Icon.Feedback.Success"]
  N179["Semantic.Color.Icon.Neutral.Default"]
  N180["Semantic.Color.Icon.Overlay.On-Overlay"]
  N181["Semantic.Color.Shadow.100"]
  N182["Semantic.Color.Shadow.200"]
  N183["Semantic.Color.Shadow.300"]
  N184["Semantic.Color.Text.Action.On-Danger"]
  N185["Semantic.Color.Text.Action.On-Disabled"]
  N186["Semantic.Color.Text.Action.On-Primary"]
  N187["Semantic.Color.Text.Action.On-Secondary"]
  N188["Semantic.Color.Text.Feedback.Danger"]
  N189["Semantic.Color.Text.Feedback.Success"]
  N190["Semantic.Color.Text.Link.Default"]
  N191["Semantic.Color.Text.Neutral.Default"]
  N192["Semantic.Color.Text.Neutral.Muted"]
  N193["Semantic.Color.Text.Neutral.Subtle"]
  N194["Semantic.Color.Text.Overlay.On-Overlay"]
  N195["Semantic.Dimension.Border.Radius.100"]
  N196["Semantic.Dimension.Border.Radius.200"]
  N197["Semantic.Dimension.Border.Radius.300"]
  N198["Semantic.Dimension.Border.Radius.400"]
  N199["Semantic.Dimension.Border.Radius.Full"]
  N200["Semantic.Dimension.Border.Width.100"]
  N201["Semantic.Dimension.Border.Width.200"]
  N202["Semantic.Dimension.Focus-Outline.Radius.Inner"]
  N203["Semantic.Dimension.Focus-Outline.Radius.Outer"]
  N204["Semantic.Dimension.Focus-Outline.Width.Inner"]
  N205["Semantic.Dimension.Focus-Outline.Width.Outer"]
  N206["Semantic.Dimension.Shadow.Blur.Bottom.100"]
  N207["Semantic.Dimension.Shadow.Blur.Bottom.200"]
  N208["Semantic.Dimension.Shadow.Blur.Bottom.300"]
  N209["Semantic.Dimension.Shadow.Blur.Default.100"]
  N210["Semantic.Dimension.Shadow.Blur.Default.200"]
  N211["Semantic.Dimension.Shadow.Blur.Default.300"]
  N212["Semantic.Dimension.Shadow.Blur.Left.100"]
  N213["Semantic.Dimension.Shadow.Blur.Left.200"]
  N214["Semantic.Dimension.Shadow.Blur.Left.300"]
  N215["Semantic.Dimension.Shadow.Blur.Right.100"]
  N216["Semantic.Dimension.Shadow.Blur.Right.200"]
  N217["Semantic.Dimension.Shadow.Blur.Right.300"]
  N218["Semantic.Dimension.Shadow.Blur.Top.100"]
  N219["Semantic.Dimension.Shadow.Blur.Top.200"]
  N220["Semantic.Dimension.Shadow.Blur.Top.300"]
  N221["Semantic.Dimension.Shadow.Spread.Bottom.100"]
  N222["Semantic.Dimension.Shadow.Spread.Bottom.200"]
  N223["Semantic.Dimension.Shadow.Spread.Bottom.300"]
  N224["Semantic.Dimension.Shadow.Spread.Default.100"]
  N225["Semantic.Dimension.Shadow.Spread.Default.200"]
  N226["Semantic.Dimension.Shadow.Spread.Default.300"]
  N227["Semantic.Dimension.Shadow.Spread.Left.100"]
  N228["Semantic.Dimension.Shadow.Spread.Left.200"]
  N229["Semantic.Dimension.Shadow.Spread.Left.300"]
  N230["Semantic.Dimension.Shadow.Spread.Right.100"]
  N231["Semantic.Dimension.Shadow.Spread.Right.200"]
  N232["Semantic.Dimension.Shadow.Spread.Right.300"]
  N233["Semantic.Dimension.Shadow.Spread.Top.100"]
  N234["Semantic.Dimension.Shadow.Spread.Top.200"]
  N235["Semantic.Dimension.Shadow.Spread.Top.300"]
  N236["Semantic.Dimension.Shadow.X.Bottom.100"]
  N237["Semantic.Dimension.Shadow.X.Bottom.200"]
  N238["Semantic.Dimension.Shadow.X.Bottom.300"]
  N239["Semantic.Dimension.Shadow.X.Default.100"]
  N240["Semantic.Dimension.Shadow.X.Default.200"]
  N241["Semantic.Dimension.Shadow.X.Default.300"]
  N242["Semantic.Dimension.Shadow.X.Left.100"]
  N243["Semantic.Dimension.Shadow.X.Left.200"]
  N244["Semantic.Dimension.Shadow.X.Left.300"]
  N245["Semantic.Dimension.Shadow.X.Right.100"]
  N246["Semantic.Dimension.Shadow.X.Right.200"]
  N247["Semantic.Dimension.Shadow.X.Right.300"]
  N248["Semantic.Dimension.Shadow.X.Top.100"]
  N249["Semantic.Dimension.Shadow.X.Top.200"]
  N250["Semantic.Dimension.Shadow.X.Top.300"]
  N251["Semantic.Dimension.Shadow.Y.Bottom.100"]
  N252["Semantic.Dimension.Shadow.Y.Bottom.200"]
  N253["Semantic.Dimension.Shadow.Y.Bottom.300"]
  N254["Semantic.Dimension.Shadow.Y.Default.100"]
  N255["Semantic.Dimension.Shadow.Y.Default.200"]
  N256["Semantic.Dimension.Shadow.Y.Default.300"]
  N257["Semantic.Dimension.Shadow.Y.Left.100"]
  N258["Semantic.Dimension.Shadow.Y.Left.200"]
  N259["Semantic.Dimension.Shadow.Y.Left.300"]
  N260["Semantic.Dimension.Shadow.Y.Right.100"]
  N261["Semantic.Dimension.Shadow.Y.Right.200"]
  N262["Semantic.Dimension.Shadow.Y.Right.300"]
  N263["Semantic.Dimension.Shadow.Y.Top.100"]
  N264["Semantic.Dimension.Shadow.Y.Top.200"]
  N265["Semantic.Dimension.Shadow.Y.Top.300"]
  N266["Semantic.Dimension.Spacing.100"]
  N267["Semantic.Dimension.Spacing.200"]
  N268["Semantic.Dimension.Spacing.300"]
  N269["Semantic.Dimension.Spacing.400"]
  N270["Semantic.Dimension.Spacing.500"]
  N271["Semantic.Dimension.Spacing.600"]
  N272["Semantic.Dimension.Spacing.700"]
  N273["Semantic.Dimension.Spacing.800"]
  N274["Semantic.Dimension.Spacing.900"]
  N275["Semantic.Font.Family.Body"]
  N276["Semantic.Font.Family.Heading"]
  N277["Semantic.Font.Line-Height.100"]
  N278["Semantic.Font.Line-Height.200"]
  N279["Semantic.Font.Line-Height.300"]
  N280["Semantic.Font.Line-Height.400"]
  N281["Semantic.Font.Line-Height.500"]
  N282["Semantic.Font.Line-Height.600"]
  N283["Semantic.Font.Line-Height.700"]
  N284["Semantic.Font.Line-Height.800"]
  N285["Semantic.Font.Line-Height.900"]
  N286["Semantic.Font.Size.100"]
  N287["Semantic.Font.Size.200"]
  N288["Semantic.Font.Size.300"]
  N289["Semantic.Font.Size.400"]
  N290["Semantic.Font.Size.500"]
  N291["Semantic.Font.Size.600"]
  N292["Semantic.Font.Size.700"]
  N293["Semantic.Font.Size.800"]
  N294["Semantic.Font.Size.900"]
  N295["Semantic.Font.Weight.Bold"]
  N296["Semantic.Font.Weight.Regular"]
  N297["Typography.Font.Family.Lora"]
  N298["Typography.Font.Family.Nunito-Sans"]
  N299["Typography.Font.Line-Height.12"]
  N300["Typography.Font.Line-Height.14"]
  N301["Typography.Font.Line-Height.16"]
  N302["Typography.Font.Line-Height.18"]
  N303["Typography.Font.Line-Height.20"]
  N304["Typography.Font.Line-Height.24"]
  N305["Typography.Font.Line-Height.28"]
  N306["Typography.Font.Line-Height.32"]
  N307["Typography.Font.Line-Height.36"]
  N308["Typography.Font.Size.12"]
  N309["Typography.Font.Size.14"]
  N310["Typography.Font.Size.16"]
  N311["Typography.Font.Size.18"]
  N312["Typography.Font.Size.20"]
  N313["Typography.Font.Size.24"]
  N314["Typography.Font.Size.28"]
  N315["Typography.Font.Size.32"]
  N316["Typography.Font.Size.36"]
  N317["Typography.Font.Weight.Bold"]
  N318["Typography.Font.Weight.Regular"]
  N1 --> N70
  N2 --> N34
  N3 --> N19
  N136 --> N67
  N137 --> N66
  N138 --> N65
  N139 --> N34
  N140 --> N7
  N141 --> N6
  N142 --> N5
  N143 --> N22
  N144 --> N21
  N145 --> N20
  N146 --> N6
  N147 --> N21
  N148 --> N27
  N149 --> N31
  N150 --> N5
  N151 --> N159
  N152 --> N29
  N153 --> N61
  N154 --> N33
  N155 --> N32
  N156 --> N19
  N157 --> N16
  N158 --> N18
  N159 --> N30
  N160 --> N19
  N161 --> N66
  N162 --> N56
  N163 --> N49
  N164 --> N14
  N165 --> N16
  N166 --> N18
  N167 --> N38
  N168 --> N41
  N169 --> N35
  N170 --> N19
  N171 --> N10
  N172 --> N19
  N173 --> N41
  N174 --> N42
  N175 --> N179
  N176 --> N66
  N177 --> N57
  N178 --> N49
  N179 --> N42
  N180 --> N19
  N181 --> N15
  N182 --> N17
  N183 --> N18
  N184 --> N19
  N185 --> N41
  N186 --> N42
  N187 --> N191
  N188 --> N66
  N189 --> N50
  N190 --> N27
  N191 --> N42
  N192 --> N41
  N193 --> N40
  N194 --> N19
  N195 --> N76
  N196 --> N77
  N197 --> N74
  N198 --> N75
  N199 --> N72
  N200 --> N79
  N201 --> N80
  N202 --> N78
  N203 --> N73
  N204 --> N80
  N205 --> N80
  N206 --> N81
  N207 --> N82
  N208 --> N83
  N209 --> N81
  N210 --> N82
  N211 --> N83
  N212 --> N81
  N213 --> N82
  N214 --> N83
  N215 --> N81
  N216 --> N82
  N217 --> N83
  N218 --> N81
  N219 --> N82
  N220 --> N83
  N221 --> N89
  N222 --> N90
  N223 --> N90
  N224 --> N91
  N225 --> N91
  N226 --> N91
  N227 --> N89
  N228 --> N90
  N229 --> N90
  N230 --> N89
  N231 --> N90
  N232 --> N90
  N233 --> N89
  N234 --> N90
  N235 --> N90
  N236 --> N99
  N237 --> N99
  N238 --> N99
  N239 --> N99
  N240 --> N99
  N241 --> N99
  N242 --> N98
  N243 --> N92
  N244 --> N95
  N245 --> N106
  N246 --> N100
  N247 --> N103
  N248 --> N99
  N249 --> N99
  N250 --> N99
  N251 --> N123
  N252 --> N116
  N253 --> N119
  N254 --> N121
  N255 --> N121
  N256 --> N123
  N257 --> N115
  N258 --> N115
  N259 --> N115
  N260 --> N115
  N261 --> N115
  N262 --> N115
  N263 --> N114
  N264 --> N107
  N265 --> N110
  N266 --> N128
  N267 --> N131
  N268 --> N134
  N269 --> N135
  N270 --> N124
  N271 --> N125
  N272 --> N126
  N273 --> N127
  N274 --> N129
  N275 --> N298
  N276 --> N297
  N277 --> N299
  N278 --> N300
  N279 --> N301
  N280 --> N302
  N281 --> N303
  N282 --> N304
  N283 --> N305
  N284 --> N306
  N285 --> N307
  N286 --> N308
  N287 --> N309
  N288 --> N310
  N289 --> N311
  N290 --> N312
  N291 --> N313
  N292 --> N314
  N293 --> N315
  N294 --> N316
