import assert from "node:assert/strict";
import { describe, it } from "node:test";

import {
  updateConsumerNameFromFigmaUrlChange,
} from "../consumer-name-suggestion";
import { suggestNameFromFigmaUrl } from "../../../../lib/figma-name-suggestion";

describe("consumer-name-suggestion", () => {
  it("suggests a readable consumer name from a Figma file URL", () => {
    assert.equal(
      suggestNameFromFigmaUrl(
        "https://www.figma.com/file/ABC123/marketing-site-redesign?node-id=0-1",
      ),
      "Marketing Site Redesign",
    );
  });

  it("keeps an auto-generated name in sync with URL changes", () => {
    assert.deepEqual(
      updateConsumerNameFromFigmaUrlChange({
        consumerName: "Marketing Site Redesign",
        consumerNameWasAutoGenerated: true,
        consumerFileUrl: "https://www.figma.com/file/ABC123/admin-dashboard-v2?node-id=0-1",
      }),
      {
        consumerName: "Admin Dashboard V2",
        consumerNameWasAutoGenerated: true,
      },
    );
  });

  it("auto-fills an empty name from the current URL", () => {
    assert.deepEqual(
      updateConsumerNameFromFigmaUrlChange({
        consumerName: "",
        consumerNameWasAutoGenerated: false,
        consumerFileUrl: "https://www.figma.com/file/ABC123/admin-dashboard-v2?node-id=0-1",
      }),
      {
        consumerName: "Admin Dashboard V2",
        consumerNameWasAutoGenerated: true,
      },
    );
  });

  it("does not overwrite a manually edited name", () => {
    assert.deepEqual(
      updateConsumerNameFromFigmaUrlChange({
        consumerName: "Internal Tools",
        consumerNameWasAutoGenerated: false,
        consumerFileUrl: "https://www.figma.com/file/ABC123/admin-dashboard-v2?node-id=0-1",
      }),
      {
        consumerName: "Internal Tools",
        consumerNameWasAutoGenerated: false,
      },
    );
  });
});
