graph TD
  undefined[primitivos_color_blanco]
  undefined[primitivos_color_negro]
  undefined[primitivos_tamano_14]
  undefined[semanticos_color_background_accent]
  undefined[semanticos_color_background_default]
  undefined[semanticos_color_foreground_accent]
  undefined[semanticos_color_foreground_default]
  undefined[semanticos_test_BORRAR]