import { suggestNameFromFigmaUrl } from "../../../lib/figma-name-suggestion";

export function updateConsumerNameFromFigmaUrlChange(args: {
  consumerName: string;
  consumerNameWasAutoGenerated: boolean;
  consumerFileUrl: string;
}): {
  consumerName: string;
  consumerNameWasAutoGenerated: boolean;
} {
  const currentName = String(args.consumerName || "").trim();
  const suggestedName = suggestNameFromFigmaUrl(args.consumerFileUrl);

  if (!currentName && suggestedName) {
    return {
      consumerName: suggestedName,
      consumerNameWasAutoGenerated: true,
    };
  }

  if (!args.consumerNameWasAutoGenerated) {
    return {
      consumerName: args.consumerName,
      consumerNameWasAutoGenerated: false,
    };
  }

  if (!suggestedName) {
    return {
      consumerName: args.consumerName,
      consumerNameWasAutoGenerated: true,
    };
  }

  return {
    consumerName: suggestedName,
    consumerNameWasAutoGenerated: true,
  };
}
